#!/bin/sh

# This script must be run from PAM stack during user login.
#
# The script mounts user home directory from NFS server. The /home directory
# is mounted from host homedir.<puavo domain>. The script relies on reverse 
# DNS query support in kerberos so that the real server name is not needed 
# for the mount.

set -e

# nx user is the FreeNX user that does not have/need a real home directory, so
# it should not be mounted
if [ "${PAM_USER}" = "nx" ]; then
  exit 0
fi

is_mounted() {
  mntpoint=$1
  mount | awk -v "mntpoint=$mntpoint" '
	    BEGIN { status = 1 }
	    $3 == mntpoint && $5 == "nfs4" { status = 0 }
	    END { exit(status) }
          '
}

PUAVO_HOSTTYPE=$(cat /etc/puavo/hosttype)
PUAVO_DOMAIN=$(cat /etc/puavo/domain)
HOMEDIR_SERVER="homedir.${PUAVO_DOMAIN}"

case "${PUAVO_HOSTTYPE}" in
  fatclient|ltspserver)
    MOUNT_OPTIONS=",soft"
    DO_MOUNT=true
    ;;
esac

if [ "${DO_MOUNT}" = "true" ]; then
  if [ "${PAM_TYPE}" = "open_session" ]; then
    # rpc.gssd needs a user principal on netboot devices as they do not have
    # machine principals.
    #
    # Install kerberos ticket to root only if root does not have a ticket
    # already.  This works around a problem, when root ticket switches
    # to another (gssd/nfs stuff does not like that (client id changes)
    # and login failures occur).
    #
    # Current kernels seem to cause problems in diskless environments when
    # SETCLIENTID or EXCHANGE_ID calls are done with GSS authentication. As
    # a temporary fix, first do a sec=sys mount of / without a kerberos
    # principal to force SETCLIENTID to be called with auth=sys.

    # First check that the dummy /mntroot mountpoint exists

    # If /etc/krb5.keytab exists, we want to do the mounts with the
    # machine credentials, but /mntroot should be done without any
    # credentials.

    if ! is_mounted "/mntroot"; then
      if [ -e /etc/krb5.keytab ]; then
        mv /etc/krb5.keytab /etc/krb5.keytab.bu
      fi
      rm -f /tmp/krb5cc_0

      mkdir -p /mntroot
      mount -t nfs4 -o sec=sys ${HOMEDIR_SERVER}:/ /mntroot
    fi

    if [ -e /etc/krb5.keytab.bu ]; then
      # Use machine credential now if it exists.
      ln -f /etc/krb5.keytab.bu /etc/krb5.keytab
    else
      # If no machine credentials exist, copy the user credential cache to
      # root.
      if [ ! -e /tmp/krb5cc_0 ]; then
        TMP_KRB5CCNAME=$(echo $KRB5CCNAME | sed -e 's/^FILE://')
        install -o root -g root -m 600 "$TMP_KRB5CCNAME" /tmp/krb5cc_0
      fi
    fi

    # Request a remote directory for the user (three second timeout, may fail)
    { echo "$PAM_USER" | nc -w 3 "$HOMEDIR_SERVER" 907; } || true

    # Then do the real mounts

    if ! is_mounted /home; then
      mount -t nfs4 -o sec=krb5,nodev,nosuid,minorversion=0${MOUNT_OPTIONS} ${HOMEDIR_SERVER}:/home /home
    fi
  fi
fi

exit 0
