#!/bin/sh

PUAVO_HOSTTYPE=$(cat /etc/puavo/hosttype)

case  "$PUAVO_HOSTTYPE" in
  fatclient|thinclient)
    xbacklight -set 100
    ;;
  laptop)
    xbacklight -set 50
    ;;
esac

# make it so that the "general login" (not guest login) is always the
# default in lightdm unity-greeter
install -d -o lightdm -g lightdm /var/lib/lightdm/.cache
install -d -o lightdm -g lightdm /var/lib/lightdm/.cache/unity-greeter

cat <<'EOF' > /var/lib/lightdm/.cache/unity-greeter/state
[greeter]
last-user=*other
EOF

chown lightdm:lightdm /var/lib/lightdm/.cache/unity-greeter/state

/usr/lib/puavo-ltsp-client/puavo-run-xrandr

exit 0
