#!/bin/sh

mkdir -p /var/lib/tftpboot
cp /usr/lib/SYSLINUX/lpxelinux.0 /var/lib/tftpboot/lpxelinux.0
cp /usr/lib/syslinux/modules/bios/chain.c32 /var/lib/tftpboot/chain.c32
cp /usr/lib/syslinux/modules/bios/ldlinux.c32 /var/lib/tftpboot/ldlinux.c32
cp /usr/lib/syslinux/modules/bios/menu.c32 /var/lib/tftpboot/menu.c32
