#!/bin/sh

set -eu

SESSION_DIR="/var/lib/puavo-desktop/users/${PAM_USER}"
RUN_DIR="/run/puavo/${PAM_USER}"

mkdir -p "${RUN_DIR}"
chown "${PAM_USER}" "${RUN_DIR}"

chown "${PAM_USER}" "${SESSION_DIR}"

echo "PUAVO_SESSION_PATH=${SESSION_DIR}/puavo_session.json"
