#!/bin/sh

# We support one method to call the init-puavo.d scripts.
# Pass "init=/sbin/init-puavo", which will execute the scripts
# in the real system and chain to /sbin/init after that.

for x in $(cat /proc/cmdline); do
    case "$x" in
        init=/sbin/init-puavo)
            LTSP_BOOT=true
            PUAVO_LTSP_BOOT=true
            break
            ;;
        superlaptop)
            SUPER_LAPTOP=true
            break
            ;;
    esac
done

test -n "$LTSP_BOOT" || exit

[ -z "${rootmnt}" ] && panic "rootmnt unknown in init-bottom"
[ -d "${rootmnt}/proc" ] || panic "rootmnt not mounted in init-bottom"
# mount writeable filesystems if / is not already mounted writeable.
if ! chroot ${rootmnt} /usr/bin/test -w "/" ; then

    image_name=$(cat "${rootmnt}/etc/ltsp/this_ltspimage_name")

    if $SUPER_LAPTOP; then
        # For super laptops do not create tmpfs but a presistent write target.
        # Put image name to target to avoid problems after image updates
        write_target="/cow-${image_name}"
        mkdir -p $write_target
    else
        write_target="/cow"
        mkdir -p $write_target
        mount -t tmpfs -o mode=0755 tmpfs /cow
    fi

    mkdir -p /rofs

    mount -o move ${rootmnt} /rofs
    if modprobe overlayfs; then
        UNION_TYPE=overlayfs
        UNION_OPTS="upperdir=${write_target},lowerdir=/rofs"
    elif modprobe aufs; then
        UNION_TYPE=aufs
        UNION_OPTS="dirs=${write_target}=rw:/rofs=ro"
    else
        . /scripts/functions
        panic "Could not load neither overlayfs nor aufs."
    fi
    mount -t ${UNION_TYPE} -o ${UNION_OPTS} ${UNION_TYPE} ${rootmnt}
    for dir in /rofs ${write_target} ; do
        mkdir -p ${rootmnt}${dir}
    	mount -o move ${dir} ${rootmnt}${dir}
    done
fi

# Copy networking configuration to the root file system
mkdir -p "$rootmnt/var/cache/ltsp/"
for netconf in /run/net-*.conf ; do
    if [ -f "$netconf" ]; then
        cp "$netconf" "$rootmnt/var/cache/ltsp/"
    fi
done
